cmake_minimum_required(VERSION 3.20)
set(basename "omega_redirect")
project(${basename} C)
set(CMAKE_C_STANDARD 17)
set(D_CWD "${CMAKE_CURRENT_SOURCE_DIR}")
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${D_CWD}/../bin)
add_executable(${basename})
set_target_properties(${basename} PROPERTIES OUTPUT_NAME "${basename}.elf")
set(CMAKE_C_FLAGS "--target=x86_64-sie-ps5 -DPS5 -fPIC -fPIE -march=znver2 -O2 -Wall")
file(GLOB SRC ${D_CWD}/source/*.c)
target_sources(${basename} PRIVATE ${SRC})
target_link_directories(${basename} PUBLIC "${PROJECT_ROOT}/lib")
target_link_libraries(${basename} PUBLIC SceLibcInternal SceSystemService SceHttp SceSsl SceNet SceSysmodule kernel_sys)
