'use strict';
// Logo di Omega: una Omega originale con l'arco spezzato da un triangolo ▶.
// MARK è trasparente (su fondo scuro), ICON ha lo sfondo dell'icona dell'app
// (favicon). Come data: URI rientrano nelle CSP con img-src data:.
const MARK_SVG = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"96 96 320 320\"><defs><linearGradient id=\"bg\" x1=\"0\" y1=\"0\" x2=\"0\" y2=\"1\"><stop offset=\"0\" stop-color=\"#151c4a\"/><stop offset=\"1\" stop-color=\"#05060d\"/></linearGradient><radialGradient id=\"lt\" cx=\".5\" cy=\".18\" r=\".85\"><stop offset=\"0\" stop-color=\"#4a5fff\" stop-opacity=\".42\"/><stop offset=\".62\" stop-color=\"#4a5fff\" stop-opacity=\"0\"/></radialGradient><linearGradient id=\"g\" x1=\"0\" y1=\"1\" x2=\"1\" y2=\"0\"><stop offset=\"0\" stop-color=\"#2fd6ff\"/><stop offset=\".55\" stop-color=\"#6a72ff\"/><stop offset=\"1\" stop-color=\"#c45bff\"/></linearGradient><radialGradient id=\"dot\" cx=\".38\" cy=\".32\" r=\".75\"><stop offset=\"0\" stop-color=\"#ffffff\"/><stop offset=\".7\" stop-color=\"#e6f6ff\"/><stop offset=\"1\" stop-color=\"#a9dcff\"/></radialGradient><filter id=\"gl\" x=\"-80%\" y=\"-80%\" width=\"260%\" height=\"260%\"><feGaussianBlur stdDeviation=\"12\" result=\"b\"/><feColorMatrix in=\"b\" type=\"matrix\" values=\"0 0 0 0 .55  0 0 0 0 .85  0 0 0 0 1  0 0 0 .9 0\" result=\"c\"/><feMerge><feMergeNode in=\"c\"/><feMergeNode in=\"SourceGraphic\"/></feMerge></filter></defs><g transform=\"translate(0.0 0.0)\"><path d=\"M366.3 236.6 A112 112 0 1 1 275.4 145.7\" fill=\"none\" stroke=\"url(#g)\" stroke-width=\"54\" stroke-linecap=\"round\"/><circle cx=\"353.6\" cy=\"158.4\" r=\"28\" fill=\"url(#dot)\" filter=\"url(#gl)\"/></g></svg>";
const ICON_SVG = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 512 512\"><defs><linearGradient id=\"bg\" x1=\"0\" y1=\"0\" x2=\"0\" y2=\"1\"><stop offset=\"0\" stop-color=\"#151c4a\"/><stop offset=\"1\" stop-color=\"#05060d\"/></linearGradient><radialGradient id=\"lt\" cx=\".5\" cy=\".18\" r=\".85\"><stop offset=\"0\" stop-color=\"#4a5fff\" stop-opacity=\".42\"/><stop offset=\".62\" stop-color=\"#4a5fff\" stop-opacity=\"0\"/></radialGradient><linearGradient id=\"g\" x1=\"0\" y1=\"1\" x2=\"1\" y2=\"0\"><stop offset=\"0\" stop-color=\"#2fd6ff\"/><stop offset=\".55\" stop-color=\"#6a72ff\"/><stop offset=\"1\" stop-color=\"#c45bff\"/></linearGradient><radialGradient id=\"dot\" cx=\".38\" cy=\".32\" r=\".75\"><stop offset=\"0\" stop-color=\"#ffffff\"/><stop offset=\".7\" stop-color=\"#e6f6ff\"/><stop offset=\"1\" stop-color=\"#a9dcff\"/></radialGradient><filter id=\"gl\" x=\"-80%\" y=\"-80%\" width=\"260%\" height=\"260%\"><feGaussianBlur stdDeviation=\"12\" result=\"b\"/><feColorMatrix in=\"b\" type=\"matrix\" values=\"0 0 0 0 .55  0 0 0 0 .85  0 0 0 0 1  0 0 0 .9 0\" result=\"c\"/><feMerge><feMergeNode in=\"c\"/><feMergeNode in=\"SourceGraphic\"/></feMerge></filter></defs><rect width=\"512\" height=\"512\" rx=\"114\" fill=\"url(#bg)\"/><rect width=\"512\" height=\"512\" rx=\"114\" fill=\"url(#lt)\"/><g transform=\"translate(0.0 0.0)\"><path d=\"M366.3 236.6 A112 112 0 1 1 275.4 145.7\" fill=\"none\" stroke=\"url(#g)\" stroke-width=\"54\" stroke-linecap=\"round\"/><circle cx=\"353.6\" cy=\"158.4\" r=\"28\" fill=\"url(#dot)\" filter=\"url(#gl)\"/></g><rect x=\"1.5\" y=\"1.5\" width=\"509\" height=\"509\" rx=\"112.5\" fill=\"none\" stroke=\"#fff\" stroke-opacity=\".07\" stroke-width=\"3\"/></svg>";
const dataUri = (svg) => `data:image/svg+xml;base64,${Buffer.from(svg).toString("base64")}`;

module.exports = { MARK_SVG, ICON_SVG, MARK_URI: dataUri(MARK_SVG), ICON_URI: dataUri(ICON_SVG) };
